# Listar usuários
GET http://localhost:8080/api/user
###

# Detalhes do usuário
GET http://localhost:8080/api/user/4
###

# Cadastrar usuário
POST http://localhost:8080/api/user
Content-Type: application/json

{

	"name": "Amanda",
	"email": "amanda@gmail.com",
	"password": "123"

}

###

# Deletar
DELETE http://localhost:8080/api/user/2
Authorization: Basic admin@fiap.com.br administrador
###

# Atualizar
PUT http://localhost:8080/api/user/4
Content-Type: application/json
Authorization: Basic admin@fiap.com.br administrador

{

	"name": "Amanda",
	"email": "amanda123@gmail.com"

}

###

# Listar tarefas
GET http://localhost:8080/api/task
###

# Detalhes da tarefa
GET http://localhost:8080/api/task/10
###

# Cadastrar tarefa
POST http://localhost:8080/api/task
Content-Type: application/json
Authorization: Basic admin@fiap.com.br administrador

{

	"title": "Corrigir bug de data",
	"description": "formatar da data no padrão BR",
	"score": 50

}

###

# Deletar
DELETE http://localhost:8080/api/task/1
Authorization: Basic admin@fiap.com.br administrador
###

# Atualizar
PUT http://localhost:8080/api/task/10
Content-Type: application/json
Authorization: Basic admin@fiap.com.br administrador

{

	"title": "Corrigir bug de datas",
	"description": "formatar da data no padrão BR"

}

###
